# This file is part of the BenGorFile package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

BenGorFile\File\Domain\Model\FileMimeType:
    type: embeddable
    fields:
        mimeType:
            column: mime_type
            length: 100
            type: string
